theme: jekyll-theme-minimal
logo: "figures/logo-j.png"
repository: visualinteractivedata/visualinteractivedata.github.io
github: [metadata]
relative_links:
  enabled: true
  collections: true
plugins: [jekyll-seo-tag]
collections:
  projects:
    output: true
    order:
      - education
      - clinical_guidelines
      - professional_course
      - cheat_sheets
      - data_comics
      - immmersive_analytics
      - networks
      - geospatial_networks
